# Generated by Django 4.1 on 2024-02-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='name',
            new_name='UniversityName',
        ),
        migrations.RemoveField(
            model_name='university',
            name='global_ranking',
        ),
        migrations.RemoveField(
            model_name='university',
            name='id',
        ),
        migrations.AddField(
            model_name='university',
            name='AdmitProbability',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='university',
            name='GPA',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='university',
            name='GREscore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='university',
            name='IELTSscore',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='university',
            name='ResearchPaper',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='university',
            name='UniversityIndex',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='university',
            name='UniversityRanking',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='university',
            name='course',
            field=models.CharField(default='CS/CE', max_length=255),
        ),
        migrations.AlterField(
            model_name='university',
            name='country',
            field=models.CharField(default='US', max_length=50),
        ),
    ]
