# Generated by Django 4.1 on 2024-02-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0002_rename_name_university_universityname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='UniversityIndex',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
